### ISSUE TITLE
Project doesn't run without specifying `BACKEND_URL`

### ISSUE THREAD

**Issue by john-rodewald** [prusa3d/Prusa-Link-Web#329]
Seems like a dependency problem. From 4eccb79c5331dcb628bedd8f81834233182430bd onwards, the project no longer runs unless `BACKEND_URL` is provided. Before the named commit, all works as expected.

`npm run start` errors out with this output:

```
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'after'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
```

This happens on both `node@v16.18.1` and `node@v18.12.1`. System is `aarch64-darwin`

After renaming the property to `onAfterSetupMiddleware`, the new error becomes:

```
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'contentBase'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
```

Again, `contentBase` is now known as `static`. I replaced `contentBase` with the following:

```
static: {
  directory: path.join(__dirname, "dist"),
},
```

Finally, the error becomes:

```
[webpack-cli] TypeError: app.use is not a function
    at devServer (/redacted/Projects/Prusa-Link-Web/tools/server/index.js:44:7)
    at Object.onAfterSetupMiddleware (/redacted/Projects/Prusa-Link-Web/webpack.config.js:183:13)
    at Server.setupMiddlewares (/redacted/Projects/Prusa-Link-Web/node_modules/webpack-dev-server/lib/Server.js:2428:20)
    at Server.initialize (/redacted/Projects/Prusa-Link-Web/node_modules/webpack-dev-server/lib/Server.js:1819:10)
    at Server.start (/redacted/Projects/Prusa-Link-Web/node_modules/webpack-dev-server/lib/Server.js:3251:16)
    at async Command.<anonymous> (/redacted/Projects/Prusa-Link-Web/node_modules/@webpack-cli/serve/lib/index.js:255:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/redacted/Projects/Prusa-Link-Web/node_modules/webpack-cli/lib/webpack-cli.js:1674:7)
```

I've resorted to running the last commit that still works (a631b1b).

**Comment by Lowentwickler** [comment]
I will check it. However, dev backend is very outdated. As soon API gets stable we will most likely update it.
